name: chat
description: Chat Plugin
version: 1.1.1
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_chat_types: ^3.3.2
  flutter_link_previewer: ^3.2.0
  flutter_lints: ^1.0.0
  file_picker: ^5.2.0
  image_picker: ^1.0.1
  mime: ^1.0.1
  open_filex: ^4.1.1
  uuid: ^3.0.6
  intl: ^0.17.0
  photo_view: ^0.14.0
  diffutil_dart: ^3.0.0
  visibility_detector: ^0.3.3
  adaptive_dialog: ^1.5.0+1
  socket_io_client: ^1.0.2
  cached_network_image: ^3.2.1
  jwt_decode: ^0.3.1
  auto_size_text: ^3.0.0
  overlay_support: ^2.0.1
  email_validator: ^2.0.1
  pull_to_refresh: ^2.0.0
  flutter_beep: ^1.0.0
  flutter_slidable: ^2.0.0
  emoji_picker_flutter: 1.3.0
  scrollable_positioned_list: ^0.3.2
  swipeable_tile: ^1.0.0+6
  flutter_file_dialog: ^2.3.0
  dio: ^4.0.6
  audioplayers: ^0.20.1
  rich_text_controller: ^1.4.0
  badges: ^2.0.2
  url_launcher: ^6.1.2
  gallery_saver: ^2.3.2
  shared_preferences: ^2.0.15
  flex_color_picker: ^3.0.2
  permission:
    git:
      url: https://github.com/leovu/permission.git
      ref: 1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: wao.chat.plugin.leovu.chat
        pluginClass: ChatPlugin
      ios:
        pluginClass: ChatPlugin
      web:
        pluginClass: ChatWeb
        fileName: chat_web.dart

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/meme/panda/
    - assets/meme/usagyuun/
    - assets/meme/mimicat/
    - assets/messages.json
    - assets/icon-chat-gpt.png
    - assets/icon-rabbit.png
    - assets/icon-panda.png
    - assets/icon-cat.png
    - assets/icon-attachment.png
    - assets/icon-edit.png
    - assets/icon-camera.png
    - assets/icon-emoji.png
    - assets/icon-chat-add.png
    - assets/icon-delivered.png
    - assets/icon-document.png
    - assets/icon-error.png
    - assets/icon-seen.png
    - assets/icon-send.png
    - assets/icon-reply.png
    - assets/icon-facebook.png
    - assets/icon-zalo.png
    - assets/icon-facebook-main.png
    - assets/icon-chathub-main.png
    - assets/icon-crown.png
    - assets/icon-star.png
    - assets/2.0x/icon-attachment.png
    - assets/2.0x/icon-delivered.png
    - assets/2.0x/icon-document.png
    - assets/2.0x/icon-error.png
    - assets/2.0x/icon-seen.png
    - assets/2.0x/icon-send.png
    - assets/3.0x/icon-attachment.png
    - assets/3.0x/icon-delivered.png
    - assets/3.0x/icon-document.png
    - assets/3.0x/icon-error.png
    - assets/3.0x/icon-seen.png
    - assets/3.0x/icon-send.png
    - assets/chat_en.json
    - assets/chat_vi.json
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
